CREATE DATABASE IF NOT EXISTS `4UNET` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `4UNET`;

CREATE TABLE IF NOT EXISTS `Clients` (
	`id` INT NOT NULL AUTO_INCREMENT,
  	`username` VARCHAR(50) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
  	`password` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Installers` (
	`id` INT NOT NULL AUTO_INCREMENT,
  	`username` VARCHAR(50) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
  	`password` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Plans` (
	`id` INT NOT NULL AUTO_INCREMENT,
    `installer_id` INT NOT NULL REFERENCES Installers.id,
  	`name` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`id`),
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

